import styles from './Home.module.scss';
function Home() {
	return (
		<div className={styles.home}>
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			Home component!
			
		</div>
	)
}

export default Home;